### ISSUE TITLE
node-gyp rebuild

### ISSUE THREAD

**Issue by robertatdi** [Cube-Controls/node-red-picubes#1]
I am trying to install node-picubes v1.0.11 using node v6.9.2 and npm v4.0.5, but continue to get a "node-gyp rebuild" error. I've tried installing the node directly on Node-Red and through the node.js command prompt, but have had the same error.

**Comment by rmvpaps** [comment]
Is this resolved? I too got this issue now with node 6.10.3 and npm 3.10.10? Some errors in make pointing to nan and addon file
It installed fine for me few months back with older nodejs. and in that node-red instance, the picube nodes are coming up fine.

**Comment by Cube-Controls** [comment]
What version of Raspbian and Raspberry Pi are you using?

**Comment by waize2** [comment]
Same problem for me in Raspian 8, Raspberry pi 3. I would appreciate a fix. thanks

**Comment by Cube-Controls** [comment]
Thanks for info, I'm working on this , I should have something for next week!

**Comment by Cube-Controls** [comment]
I have tested and there is problem with Node-RED that comes with latest Jessy Raspbian, for some reason native modules are not supported.
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=127939

I tested with http://thethingbox.io version of Node-Red image and that one works no problem, for now I suggest to use this node-red image until I find fix for latest versions!

**Comment by robertatdi** [comment]
I have been trying to utilize the delay-on-off node, but am having an issue when initializing node-red.
"[delay-on-off] Error" Cannot find module 'time' (line:3)"
Do you have any idea as to why this is happening?

**Comment by Cube-Controls** [comment]
This issue is fixed!
